services:
  spring-boot-oauth2-auth-server:
    container_name: spring-boot-oauth2-auth-server
    build:
      context: ./
      dockerfile: Dockerfile
    image: "spring-boot-oauth2-auth-server1:latest"
    restart: unless-stopped
    env_file: docker.env
    volumes:
      - ./certificates:/certs
      - ./templates:/template-assets
    networks:
      - authservernetwork
    ports:
      - "5020:5020"

  spring-boot-oauth2-auth-server-db:
    container_name: spring-boot-oauth2-auth-server-db
    image: postgres
    restart: unless-stopped
    networks:
      authservernetwork:
        aliases:
          - authserverdb
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password


networks:
  authservernetwork:
    external: false
    name: authservernetwork
