name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build Backend App
        run: cd spring-boot-oauth2-auth-server && mvn clean package && cd ../

      - name: Build Gateway App
        run: cd gateway && mvn clean package && cd ../

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build Admin Panel SPA
        run: cd auth-kit-app-frontend && gradle clean zip --no-daemon && cd ../
